version: "3.9"

services:
  gpu-monitor:
    image: miracle996/gpu-monitor:latest
    container_name: gpu-monitor
    ports:
      - "5000:5000"
    volumes:
      - ./config/:/app/config/
    environment:
      - TZ=Asia/Shanghai
    restart: always
